--- #YAML:1.0
name: CGI-Application-Plugin-Session
version: 0.04
author: Cees Hek <cees@crtconsulting.ca>
abstract: |-
  Plugin that adds session support to CGI::Application
license: perl
requires:
  CGI::Application: 3.21
  CGI::Session: 3.95
provides:
  CGI::Application::Plugin::Session:
    file: lib/CGI/Application/Plugin/Session.pm
    version: 0.04
generated_by: Module::Build version 0.25
