---
abstract: 'Plugin that adds session support to CGI::Application'
author:
  - 'Cees Hek <ceeshek@gmail.com>'
build_requires:
  Test::More: 1.001002
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CGI-Application-Plugin-Session
requires:
  CGI::Application: 3.21
  CGI::Session: 4.48
  File::Spec: 0
  Scalar::Util: 0
resources:
  homepage: https://github.com/frioux/CGI-Application-Plugin-Session
  repository: https://github.com/frioux/CGI-Application-Plugin-Session.git
version: 1.05
