---
name: CGI-Application-Plugin-Session
version: 0.07
author:
  - Cees Hek <cees@crtconsulting.ca>
abstract: Plugin that adds session support to CGI::Application
license: perl
requires:
  CGI::Application: 3.21
  CGI::Session: 3.95
  File::Spec: 0
provides:
  CGI::Application::Plugin::Session:
    file: lib/CGI/Application/Plugin/Session.pm
    version: 0.07
generated_by: Module::Build version 0.26
